language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script:
  - pytest
