name: Workflow for Codecov example-python
on: [push, pull_request]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install '.[test]'
      - name: Install coveralls
        run: pip install coveralls
      - name: Run tests and collect coverage
        run: |
          pytest
          coverage xml
          coveralls
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}

