name: Build and push coverage to Codecov
on: [push, pull_request]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install '.[test]'
      - name: Run tests and collect coverage
        run: |
          pytest
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Install requests types
        run: python3 -m pip install types-requests
      # - name: Run mypy
      #   uses: jpetrucciani/mypy-check@master
      #   with:
      #     path: 'src/'
